python /home/ubuntu/wangchenyang/rlzero/rlfromscratch/collect.py  \
    --run-dir /home/ubuntu/wangchenyang/RLfromscratch/outputs/SAC-search/2026-07-13_07-54-20/seed-4_name-Hopper-v5 \
    --model best \
    --output /home/ubuntu/wangchenyang/rlzero/rlfromscratch/outputs/collected/SAC-Mujoco/sac_hopper_best_100eps \
    --collect-episodes 100 \
    --num-testing-envs 8 \
    --seed 0 \
    --overwrite \
    --min-reward 0 \
    --min-length 0 \
    --test-epsilon 0.0
